epam/edp-cluster-add-ons

- README.md
- add-ons/keycloak/Chart.yaml
- add-ons/keycloak/README.md
- add-ons/keycloak/values.yaml
Update keycloak to the latest stable version
Address the issue by adding flags:
-Dkeycloak.connectionsHttpClient.default.expect-continue-enabled=true
-Dkeycloak.connectionsHttpClient.default.reuse-connections=false
Fixes #88 
> chore: Update keycloak to the latest stable version (#88)

- README.md
- add-ons/opensearch/Chart.yaml
- add-ons/opensearch/README.md
Updated dependencies in Chart.yaml for the Opensearch chart:
- opensearch to version 2.20.0
- opensearch-dashboards to version 2.18.0
- fluent-bit to version 0.46.7
Fixes # (issue)
> chore: Update Opensearch chart version

- README.md
- add-ons/nexus/Chart.yaml
- add-ons/nexus/README.md
- add-ons/nexus/values.yaml
Updated Nexus chart to use image version 3.69.0.
Fixes #85
> chore: Update nexus image version to 3.69.0 (#85)

- README.md
- add-ons/fluent-bit/Chart.yaml
- add-ons/fluent-bit/README.md
- add-ons/fluent-bit/values.yaml
- add-ons/opensearch/Chart.yaml
- add-ons/opensearch/README.md
- add-ons/opensearch/values.yaml
Fluenbit has k8s-nginx parser out of the box
Fixes #83 
> chore: Remove duplicate parser from fluent-bit (#83)

- README.md
- add-ons/dependency-track/Chart.yaml
- add-ons/dependency-track/README.md
- add-ons/dependency-track/templates/oidc/keycloak-client-dependency-track.yaml
- add-ons/dependency-track/templates/postgres.yaml
- add-ons/dependency-track/values.yaml
Updated Dependency-track chart version to 0.9.1.
Fixes #86
> chore: Update Dependency-track chart version to 0.9.1 (#86)

- README.md
- add-ons/dependency-track/Chart.yaml
- add-ons/dependency-track/README.md
- add-ons/dependency-track/values.yaml
Disable api-server persistentVolume due to use of external PostgreSQL database (PGO)
> chore: Disable api-server persistentVolume due to use of external database (#86)

- README.md
- add-ons/edp/Chart.yaml
- add-ons/edp/README.md
- add-ons/edp/values.yaml
- add-ons/extensions-oidc/Chart.yaml
- add-ons/extensions-oidc/README.md
- add-ons/sonar-operator/Chart.yaml
- add-ons/sonar-operator/README.md
- add-ons/sonar-operator/values.yaml
Align edp operators version and bump KubeRocketCI platform version to 3.9.0.
Fixes #99
> chore: Align operators version and bump KubeRocketCI version (#99)

- add-ons/sonar-operator/templates/sonar/qualitygate_edp.yaml
> chore: Align sonar QG by complies

- add-ons/prometheus-operator/Chart.yaml
- add-ons/prometheus-operator/README.md
> chore: Update prometheus-operator version (#74)

- README.md
- add-ons/fluent-bit/Chart.yaml
- add-ons/fluent-bit/README.md
- add-ons/opensearch/Chart.yaml
- add-ons/opensearch/README.md
Update logging stack
Fixes #104 
> chore: Update logging stack to the latest stable versions (#104)

- add-ons/argo-cd/README.md
- add-ons/argo-cd/templates/appProject.yaml
- add-ons/argo-cd/values.yaml
> chore: Allow run terminal in Argo UI

- add-ons/fluent-bit/README.md
- add-ons/fluent-bit/README.md.gotmpl
> docs: Update README fluent-bit config for events (#108)

- add-ons/fluent-bit/README.md
- add-ons/fluent-bit/README.md.gotmpl
> fix: Fix ascii art diagram for fluentbit config for events (#108)

- README.md
- add-ons/prometheus-operator/Chart.yaml
- add-ons/prometheus-operator/README.md
Updated kube-prometheus-stack chart version to v61.3.2.
Fixes #116 
> chore: Update kube-prometheus-stack chart version (#116)

- add-ons/capsule/README.md
- add-ons/capsule/values.yaml
Implement cert-manager integration for capsule.
Fixes #118 
> chore: Implement cert-manager integration for capsule (#118)

- add-ons/report-portal/README.md
- add-ons/report-portal/templates/external-secrets/externalsecret-reportportal-keycloak-client-creds.yaml
- add-ons/report-portal/templates/saml/keycloak-client-report-portal.yaml
- add-ons/report-portal/templates/saml/keycloak-client-scope-report-portal.yaml
- add-ons/report-portal/values.yaml
Implemented SAML authentication via Keycloak for Report-portal chart.
Fixes #120
> feat: Implement SAML authentication for report-portal (#120)

- add-ons/awx-operator/README.md
- add-ons/awx-operator/templates/external-secrets/awx-admin-password.yaml
- add-ons/awx-operator/values.yaml
Added external secret for AWX admin user
Fixes #122 
> chore: Add external secret for AWX admin user (#122)

- add-ons/nexus-operator/templates/nexus/repository/maven/edp-maven-releases.yaml
Changed deployment policy for edp-maven-releases nexus repo from 'Allow redeploy' to 'Disable redeploy'.
Fixes #125
> chore: Change deploy policy for edp-maven-releases nexus repo (#125)

- add-ons/nexus-operator/templates/nexus/repository/yum/edp-yum-blobstore.yaml
- add-ons/nexus-operator/templates/nexus/repository/yum/edp-yum-proxy.yaml
- add-ons/nexus-operator/templates/nexus/repository/yum/edp-yum-releases.yaml
- add-ons/nexus-operator/templates/nexus/repository/yum/edp-yum-snapshots.yaml
> feat: Provision yum repositories in Nexus Repository Manager (#125)

- add-ons/nexus-operator/templates/nexus/repository/dotnet/edp-dotnet-releases.yaml
- add-ons/nexus-operator/templates/nexus/repository/npm/edp-npm-releases.yaml
- add-ons/nexus-operator/templates/nexus/repository/python/edp-python-releases.yaml
Changed deploy policy to 'Disable redeploy' for all release nexus repositories.
Fixes #125 
> chore: Change deploy policy for all release nexus repos (#125)

- add-ons/extensions-oidc/Chart.yaml
- add-ons/extensions-oidc/README.md
- add-ons/extensions-oidc/templates/_helpers.tpl
- add-ons/extensions-oidc/templates/broker/keycloak-client-shared.yaml
- add-ons/extensions-oidc/templates/broker/keycloak-realm.yaml
- add-ons/extensions-oidc/templates/external-secrets/externalsecret-keycloak-client-shared-secret.yaml
- add-ons/extensions-oidc/templates/external-secrets/keycloak-client-eks-secret.yaml
- add-ons/extensions-oidc/templates/keycloak.yaml
- add-ons/extensions-oidc/templates/kubernetes/clusterrolebinding-admin.yaml
- add-ons/extensions-oidc/templates/kubernetes/keycloak-client.yaml
- add-ons/extensions-oidc/templates/kubernetes/keycloak-clientscope.yaml
- add-ons/extensions-oidc/templates/kubernetes/keycloak-realmgroups-admins.yaml
- add-ons/extensions-oidc/templates/kubernetes/keycloak-realmgroups-builders.yaml
- add-ons/extensions-oidc/templates/kubernetes/keycloak-realmgroups-cluster-admins.yaml
- add-ons/extensions-oidc/templates/kubernetes/keycloak-realmgroups-deployers.yaml
- add-ons/extensions-oidc/templates/kubernetes/keycloak-realmgroups-developers.yaml
- add-ons/extensions-oidc/templates/kubernetes/keycloak-realmgroups-viewers.yaml
- add-ons/extensions-oidc/templates/shared/keycloak-realm.yaml
- add-ons/extensions-oidc/templates/shared/shared-idp.yaml
- add-ons/extensions-oidc/values.yaml
- add-ons/keycloak-operator/Chart.yaml
- add-ons/keycloak-operator/README.md
- add-ons/keycloak-operator/values.yaml
- chart/templates/extensions-oidc.yaml
> chore: Update extensions-oidc application (#129)

- add-ons/oauth2-proxy/Chart.yaml
- add-ons/oauth2-proxy/README.md
- add-ons/oauth2-proxy/templates/external-secrets/oauth2-proxy.yaml
- add-ons/oauth2-proxy/templates/external-secrets/secretstore-aws.yaml
- add-ons/oauth2-proxy/templates/external-secrets/secretstore-generic.yaml
- add-ons/oauth2-proxy/templates/external-secrets/serviceaccount.yaml
- add-ons/oauth2-proxy/templates/keycloak/clientscope-oauth2-proxy.yaml
- add-ons/oauth2-proxy/templates/keycloak/keycloakclient-oauth2-proxy.yaml
- add-ons/oauth2-proxy/values.yaml
- chart/README.md
- chart/templates/oauth2-proxy.yaml
- chart/values.yaml
OAuth2Proxy is added as a component to the edp-cluster-add-ons repo.
Fixes # (issue)
Deployed with test values on development environment
> chore: Add oauth2-proxy (#131)

- add-ons/capsule/README.md
- add-ons/capsule/values.yaml
Disable Cert-manager integration with Capsule.
Fixes #139
> chore: Disable Cert-manager integration for Capsule (#139)

- add-ons/sonar-operator/templates/external-secrets/externalsecret-sonar-view-password-secret.yaml
- add-ons/sonar-operator/templates/sonar/permission_template.yaml
- add-ons/sonar-operator/templates/sonar/user_view.yaml
> chore: Align Widgets Users Permissions Across KRCI Platform

- README.md
- add-ons/nexus/Chart.yaml
- add-ons/nexus/README.md
- add-ons/nexus/values.yaml
> chore: Bump nexus version

- pull_request_template.md
Updated the Pull Request template to include "Enhancement" as a new change type.
Fixes #24
> chore: Update Pull Request Template (#24)

- README.md
- add-ons/krakend/Chart.yaml
- add-ons/krakend/README.md
- add-ons/krakend/templates/external-secrets/krakend.yaml
- add-ons/krakend/templates/external-secrets/secretstore-aws.yaml
- add-ons/krakend/templates/external-secrets/secretstore-generic.yaml
- add-ons/krakend/templates/external-secrets/serviceaccount.yaml
- add-ons/krakend/values.yaml
- chart/README.md
- chart/templates/krakend.yaml
- chart/values.yaml
> chore: Add krakend(#148)

- chart/templates/krakend.yaml
> fix: Make argocd project a configurable value for karend(#148)

- add-ons/kuberocketci-rbac/templates/kubernetes/clusterrolebinding-admin.yaml
> fix: Update cluster role name

- add-ons/sonar-operator/templates/sonar/group_edp.yaml
> chore: Remove unused group in sonar

- add-ons/sonar-operator/templates/sonar/user_ci.yaml
- add-ons/sonar-operator/templates/sonar/view_group.yaml
> fix: Update rbac model for sonar

- add-ons/argo-cd/templates/oidc/keycloak-client.yaml
> fix: Parameterize argocd url into oidc template

- add-ons/argo-cd/README.md
- add-ons/argo-cd/values.yaml
> chore: Add exclusions to ignore pipelineruns in Argo CD (#129)

- add-ons/atlantis/README.md
- add-ons/atlantis/templates/external-secrets/atlantis-webhook.yaml
- add-ons/atlantis/templates/external-secrets/secretstore-generic.yaml
- add-ons/atlantis/templates/external-secrets/secretstore.yaml
- add-ons/atlantis/templates/external-secrets/serviceaccount.yaml
- add-ons/atlantis/values.yaml
- add-ons/awx-operator/templates/external-secrets/secretstore.yaml
- add-ons/oauth2-proxy/README.md
- add-ons/oauth2-proxy/templates/external-secrets/serviceaccount.yaml
- add-ons/oauth2-proxy/values.yaml
> chore: Align external-secret operator usage (#160)

- add-ons/edp/Chart.yaml
- add-ons/edp/README.md
- add-ons/edp/values.yaml
> chore: Bump KubeRocketCI platform version (#162)

- clusters/core/bootstrap-addons.yaml
> chore: Set correct path to apps (#164)

- argo-cd/templates/appProjectCore.yaml
- argo-cd/templates/appProjectKRCI.yaml
- clusters/core/addons/argo-cd/templates/appProject.yaml
- clusters/core/apps/README.md
- clusters/core/apps/templates/kuberocketci-pipelines.yaml
- clusters/core/apps/values.yaml
> chore: Set correct path to git repos (#164)

- clusters/core/addons/capsule-tenant/README.md
- clusters/core/addons/capsule-tenant/krci-tenant.yaml
- clusters/core/addons/capsule/README.md
- clusters/core/addons/capsule/values.yaml
> chore: Align Capsule Tenant provisioning (#164)

- argo-cd/README.md
- argo-cd/templates/appProjectKRCI.yaml
- argo-cd/templates/oidc/keycloak-group-krci.yaml
- argo-cd/templates/oidc/keycloak-group-readonly.yaml
- argo-cd/values.yaml
- clusters/core/addons/argo-cd/README.md
- clusters/core/addons/argo-cd/templates/appProject.yaml
- clusters/core/addons/argo-cd/templates/oidc/keycloak-group-krci.yaml
- clusters/core/addons/argo-cd/templates/oidc/keycloak-group-readonly.yaml
- clusters/core/addons/argo-cd/values.yaml
- clusters/core/addons/kuberocketci-rbac/templates/kubernetes/keycloak-realmgroups-admins.yaml
- clusters/core/addons/kuberocketci-rbac/templates/kubernetes/keycloak-realmgroups-developers.yaml
- clusters/core/addons/kuberocketci-rbac/templates/kubernetes/keycloak-realmgroups-viewers.yaml
> chore: Align Argo CD RBAC (#164)

- README.md
- hack/update_readme.py
> chore: Align README.md (#164)

- README.md
> chore: Align path to files in README.md (#164)

- clusters/core/apps/README.md
- clusters/core/apps/templates/awx-operator.yaml
- clusters/core/apps/values.yaml
Add ArgoCD Application CR for awx-operator
Fixes #122
> chore: Add ArgoCD Application for awx-operator (#122)

- clusters/core/addons/opensearch/templates/external-secrets/externalsecret-dashboard.yaml
Clarify Cookie Secret Usage in OpenSearch chart.
Fixes #177
> chore: Clarify Cookie Secret Usage in OpenSearch (#177)

- argo-cd/templates/appProjectCore.yaml
- argo-cd/templates/appProjectKRCI.yaml
This pull request updates the SSH URLs in the sourceRepos section of ArgoCD project configurations (appProjectCore.yaml and appProjectKRCI.yaml) to align with the main approach for specifying Git server connections.
Deploy on the dev environment.
> chore: Align Project values for main ArgoCD(#181)

- argo-cd/templates/appProjectCore.yaml
- argo-cd/templates/appProjectKRCI.yaml
- clusters/core/apps/values.yaml
- clusters/core/bootstrap-addons.yaml
This pull request updates the SSH URLs in the source section of ArgoCD project configurations (bootstrap-addons.yaml, appProjectCore.yaml, appProjectKRCI.yaml, and values.yaml) to align with the standard approach for specifying Git server connections. Additionally, the account name in the SSH URLs was updated to meet documentation consistency requirements. Detailed comments were added to clarify the format and purpose of the sourceRepos and repoUrl fields.
Deploy on the dev environment.
> chore: Align app of apps repoUrl to main approach(#181)

- clusters/core/addons/sonar/README.md
- clusters/core/addons/sonar/values.yaml
> chore: Upgrade Sonar Plugins to Latest Stable Versions

- argo-cd/templates/external-secrets/serviceaccount.yaml
- clusters/core/apps/templates/cert-manager.yaml
- clusters/core/bootstrap-addons.yaml
> fix: Fix typo in add-ons

- clusters/core/addons/krakend/README.md
- clusters/core/addons/krakend/README.md.gotmpl
Update README.md.gotmpl template for KrakenD
Fixes #185
> chore: Update KrakenD README.md template (#185)

- clusters/core/addons/argo-cd/README.md
- clusters/core/addons/argo-cd/templates/appProject.yaml
- clusters/core/addons/argo-cd/values.yaml
> chore: Update ArgoCD RBAC to avoid exec error

- README.md
- clusters/core/addons/tekton-custom-task/Chart.yaml
- clusters/core/addons/tekton-custom-task/README.md
- clusters/core/addons/tekton-custom-task/values.yaml
- clusters/core/apps/README.md
- clusters/core/apps/templates/tekton-custom-task.yaml
- clusters/core/apps/values.yaml
Add Tekton Custom Task add-on support
Fixes #200
> chore: Add Tekton Custom Task integration (#200)

- clusters/core/addons/nexus-operator/README.md
Update readme
Related issue #193
> docs: Update Nexus Operator version (#193)

- clusters/core/addons/tekton/chains.yaml
- clusters/core/addons/tekton/interceptors.yaml
- clusters/core/addons/tekton/pipelines.yaml
- clusters/core/addons/tekton/triggers.yaml
Bump Tekton components versions (pipelines, triggers, chains, interceptors)
Fixes #203
> chore: Bump Tekton components versions (#203)

- clusters/core/addons/ingress-nginx/README.md
- clusters/core/addons/ingress-nginx/values.yaml
> fix: Align metrics parameter in nginx ingress

- clusters/core/addons/storage-class/storageClass.yaml
- clusters/core/addons/storage-class/storageclass-gp3.yaml
Enable volume expansion in StorageClass manifests
Fixes #207
> chore: Enable volume expansion for StorageClasses (#207)

- clusters/core/addons/karpenter-np/Chart.yaml
- clusters/core/addons/karpenter-np/README.md
- clusters/core/addons/karpenter-np/templates/cronjob.yaml
- clusters/core/addons/karpenter-np/templates/node-class.yaml
- clusters/core/addons/karpenter-np/templates/nodepool-cm.yaml
- clusters/core/addons/karpenter-np/templates/nodepool.yaml
- clusters/core/addons/karpenter-np/templates/rbac.yaml
- clusters/core/addons/karpenter-np/values.yaml
- clusters/core/addons/karpenter/Chart.yaml
- clusters/core/addons/karpenter/README.md
- clusters/core/addons/karpenter/values.yaml
- clusters/core/addons/keda-tenants/Chart.yaml
- clusters/core/addons/keda-tenants/README.md
- clusters/core/addons/keda-tenants/README.md.gotmpl
- clusters/core/addons/keda-tenants/templates/cd-pipeline-operator.yaml
- clusters/core/addons/keda-tenants/templates/codebase-operator.yaml
- clusters/core/addons/keda-tenants/templates/git-providers.yaml
- clusters/core/addons/keda-tenants/templates/portal.yaml
- clusters/core/addons/keda-tenants/templates/tekton-interceptor.yaml
- clusters/core/addons/keda-tenants/values.yaml
- clusters/core/addons/keda/Chart.yaml
- clusters/core/addons/keda/README.md
- clusters/core/addons/keda/values.yaml
- clusters/core/apps/README.md
- clusters/core/apps/templates/karpenter-np.yaml
- clusters/core/apps/templates/karpenter.yaml
- clusters/core/apps/templates/keda-tenants.yaml
- clusters/core/apps/templates/keda.yaml
- clusters/core/apps/values.yaml
> feat: Add autoscaler for KRCI platform

- README.md
- clusters/core/addons/dependency-track/Chart.yaml
- clusters/core/addons/dependency-track/README.md
- clusters/core/addons/dependency-track/templates/postgres.yaml
- clusters/core/addons/dependency-track/values.yaml
Bump DepTrack to 4.12.2
Align Postgres operator configuration add default images
Fixes (#213)
Deployed on test environment
> chore: Bump DepTrack to 4.12.2 align PGO values(#213)

- README.md
- clusters/core/addons/karma-dashboard/Chart.yaml
- clusters/core/addons/karma-dashboard/README.md
- clusters/core/addons/karma-dashboard/values.yaml
- clusters/core/apps/README.md
- clusters/core/apps/templates/karma-dashboard.yaml
- clusters/core/apps/values.yaml
Implement Karma dashboard helm chart
Fixes #221
> chore: Implement Karma dashboard (#221)

- clusters/core/addons/nexus-operator/templates/nexus/repository/container/krci-container-cleanup-policy.yaml
Added cleanup policy for docker containers
Fixes (#213)
Deployed on develop environment with test nexus and nexus-operator.
> chore: Add nexus cleanup policy for containers

- README.md
- clusters/core/addons/dependency-track/Chart.yaml
- clusters/core/addons/dependency-track/README.md
- clusters/core/addons/dependency-track/values.yaml
Please include a summary of the change and why it is needed.
Updates the Dependency Track helm chart to v0.26.0 to incorporate the latest enhancements and dependency updates from the upstream. This change aligns with the goal of keeping our cluster add-ons up-to-date with the latest stable versions.
Fixes # (GitHub Issue)
> feat: update Dependency Track helm chart to v0.26.0

- clusters/core/addons/ingress-nginx/Chart.yaml
This PR updates the ingress-nginx Helm chart to version 4.12.0 and application version to 1.12.0.
Fixes #233
> Update ingress-nginx Helm chart to v4.12.0

- clusters/core/addons/atlantis/Chart.yaml
This pull request updates the Atlantis Helm chart and application versions in the repository to ensure compatibility and access to the latest features.
Fixes #239
I have tested the updated Helm chart deployment in a local Kubernetes cluster to verify compatibility and functionality.
This update includes the following changes:
- Upgraded Helm chart version from `5.8.0` to `5.14.0`.
- Upgraded application version from `v0.30.0` to `v0.33.0`.
Let me know if you need further assistance or additional changes to the PR!
> fix: Update Atlantis Helm chart to v5.14.0 and app to v0.33.0 (#239)

- clusters/core/apps/README.md
- clusters/core/apps/values.yaml
> chore: Enable Prefix for KRCI Dependent Tools

- .github/workflows/check-helm-dependencies.yml
- Makefile
- hack/check_dependencies.sh
Add a Makefile command to check Helm dependencies versions (`make check-dependencies`)
Fixes #245
> chore: Add a Makefile command to check Helm dependencies versions (#245)

- clusters/core/addons/ingress-nginx-external/Chart.yaml
- clusters/core/addons/ingress-nginx-external/README.md
- clusters/core/addons/ingress-nginx/Chart.yaml
- clusters/core/addons/ingress-nginx/README.md
Update ingress-nginx chart version (to v.4.12.1)
Fixes #249
> chore: Update ingress-nginx chart version (#249)

- clusters/core/addons/ingress-nginx/values.yaml
Add annotations-risk-level flag for ingress-nginx
Fixes #249 
> Add annotations risk level for ingress-nginx

- clusters/core/addons/sonar/README.md
- clusters/core/addons/sonar/templates/external-secrets/monitoring-passcode.yaml
- clusters/core/addons/sonar/templates/external-secrets/secretstore-aws.yaml
- clusters/core/addons/sonar/templates/external-secrets/secretstore-generic.yaml
- clusters/core/addons/sonar/templates/external-secrets/serviceaccount.yaml
- clusters/core/addons/sonar/values.yaml
Add `monitoringPasscode` Secret Fields to SonarQube Helm chart.
Fixes #260
> chore: Add monitoringPasscode Secret Fields to SonarQube (#260)

- README.md
- clusters/core/addons/kuberocketci/Chart.yaml
- clusters/core/addons/kuberocketci/README.md
Update KubeRocketCI chart version to v.3.11.2.
Fixes #258
> chore: Update KubeRocketCI chart version (#258)

- clusters/core/addons/karpenter-np/README.md
- clusters/core/addons/kuberocketci-rbac/templates/kubernetes/keycloak-client.yaml
> chore: Align redirectUris(#270)

- clusters/core/addons/atlantis/Chart.yaml
- clusters/core/addons/atlantis/README.md
- clusters/core/addons/atlantis/templates/external-secrets/atlantis-creds.yaml
- clusters/core/addons/atlantis/templates/external-secrets/oauth2-proxy-secret.yaml
- clusters/core/addons/atlantis/templates/oidc/keycloak-client-secret.yaml
- clusters/core/addons/atlantis/templates/oidc/keycloakclient-oauth2-proxy.yaml
- clusters/core/addons/atlantis/values.yaml
Support Basic and OIDC authentication types for Atlantis.
Fixes #256
> chore: Support Basic and OIDC authentication for Atlantis (#256)

- README.md
- clusters/core/addons/moon/Chart.yaml
- clusters/core/addons/moon/README.md
- clusters/core/addons/moon/values.yaml
- clusters/core/apps/README.md
- clusters/core/apps/templates/moon.yaml
- clusters/core/apps/values.yaml
> chore: Add Moon deploy templates(#272)

- clusters/core/addons/kuberocketci-rbac/templates/shared/shared-idp.yaml
> chore: Add picture mappers in KeycloakRealmIdentityProvider (#275)

- .github/workflows/check-helm-dependencies.yml
- Makefile
- hack/check_dependencies.py
Allow to run check in parallel
Fixes #(279)
> chore: Refactor Helm dependency by enabling running in parallel (#279)

- .github/workflows/chart-testing.yml
> chore(ci): Update task version for chart testing flow (#285)

- clusters/core/addons/atlantis/README.md
- clusters/core/addons/atlantis/values.yaml
Set default `atlantisUrl` value for Atlantis Helm chart.
Fixes #289
> chore: Add atlantisUrl field to values.yaml

- .github/prompts/create-github-issue.prompt.md
- .github/prompts/create-github-pr.prompt.md
This PR updates function names in GitHub prompt files to match current naming conventions. The changes remove the 'bb7_' prefix from function names in `.github/prompts/create-github-issue.prompt.md` and `.github/prompts/create-github-pr.prompt.md`.
Additionally, this PR enhances the `create-github-pr.prompt.md` with:
- Instructions for checking and creating feature branches following proper naming conventions
- Clearer push instructions emphasizing the use of feature branches only
- Improved branch management guidance for both workflow options
- Added explicit confirmation step for reviewing PR draft before submission
Closes #296
- Files have been reviewed for correctness and consistency
- Naming conventions have been standardized across prompt files
> chore(github): Update function names in GitHub prompt files (#296)

- README.md
- clusters/core/addons/karpenter/Chart.yaml
- clusters/core/addons/karpenter/README.md
Update Karpenter version (to `v1.6.1`).
Fixes #317
> chore: Update Karpenter version

- clusters/core/addons/sonar/Chart.yaml
- clusters/core/addons/sonar/README.md
- clusters/core/addons/sonar/values.yaml
> chore: Bump sonarqube version

- clusters/core/addons/capsule/Chart.yaml
- clusters/core/addons/capsule/README.md
> chore: Update capsule to 0.7.4

- README.md
- clusters/core/addons/pgadmin/Chart.yaml
- clusters/core/addons/pgadmin/README.md
Update `pgadmin4` chart version (to `v1.49.0`).
Fixes #342
> chore: Update pgadmin4 chart version

- clusters/core/addons/vault-kms/Chart.yaml
- clusters/core/addons/vault-kms/README.md
- clusters/core/addons/vault-okd/Chart.yaml
- clusters/core/addons/vault-okd/README.md
- clusters/core/addons/vault-operator/Chart.yaml
- clusters/core/addons/vault-operator/README.md
- clusters/core/addons/vault/Chart.yaml
- clusters/core/addons/vault/README.md
> chore: Bump Vault to 1.20.1

- clusters/core/addons/awx-operator/templates/init-job/init-job.yaml
- clusters/core/addons/nexus-ce/values.yaml
- clusters/core/addons/report-portal/templates/init-job/init-job.yaml
Migrated images from **bitnami** to **bitnamilegacy** in order to align with Bitnami’s transition.  
This change updates  primary `edp-cluster-addons` to ensure continued compatibility and support.  
Fixes #360
- Verified deployment of updated addons in a test environment.  
- Ensured all containers successfully pull Bitnami Legacy images.  
- Checked that no runtime issues occurred after migration.
> chore: Migrate images bitnami to bitnamilegacy(#360)

- clusters/core/addons/karpenter-np/templates/node-class.yaml
- clusters/core/addons/karpenter/README.md
- clusters/core/addons/karpenter/values.yaml
> chore: Update Karpenter role name

- clusters/core/addons/kuberocketci/Chart.yaml
- clusters/core/addons/kuberocketci/README.md
> chore: Bump KRCI to 3.12.2 (#330)

- clusters/core/addons/kuberocketci/Chart.yaml
- clusters/core/addons/kuberocketci/README.md
> chore: Bump KRCI to 3.12.3 (#330)
